 5 N = INT(RND(10)*100)
 10 PRINT "INGRESE UN NUMERO"
 20 INPUT A
 25 Z = Z + 1
 30 IF A > N THEN PRINT "MI NUMERO ES MENOR"
 40 IF A < N THEN PRINT "MI NUMERO ES MAYOR"
 50 IF A = N THEN GOTO 70
 60 GOTO 20
 70 PRINT "BRAVO!"
 80 PRINT "ESE ES MI NUMERO!!!"
 90 PRINT "LO HAS LOGRADO EN " + STR$(Z) + " INTENTOS"